<?php

/* @var $block Eezy_Didyouknow_Block_Random */
$block = $this;
?>
<div id="" class="didyouknow random">
	<div>
		<div><?php echo $this->getQuote()->getContent(); ?></div>
	</div>
</div>
<script>
setInterval(function(){
	(function($){
		$.ajax({
			url : "?isAjax=1",
			success: function(data){
				$(".didyouknow.random").animate({marginLeft: '-70px', 'opacity' : 0}, 500, function(){
					$("div > div", this).html(data);
					$(this).animate({marginLeft: '0px', 'opacity' : 1}, 500);
				});
			}
		});
	})(jQuery);
}, 5000);
</script>