<?php

/* @var $block Eezy_Didyouknow_Block_Random */
$block = $this;
?>
<div id="" class="didyouknow random">
	<div>
		<div><?php echo $this->getQuote()->getContent(); ?></div>
	</div>
</div>
<script>
(function($){
	var quotes = <?php echo $this->getJsonQuotes() ?>;
	var count = 0;
	setInterval(function(){
		count++;
		if(count >= quotes.length){

		}
		var quote = quotes[Math.floor(Math.random() * quotes.length)];
		$(".didyouknow.random").animate({marginLeft: '-70px', 'opacity' : 0}, 500, function(){
			$("div > div", this).html(quote);
			$(this).animate({marginLeft: '0px', 'opacity' : 1}, 500);
		});
	}, <?php echo $block->getInterval() ? $block->getInterval() : 20000 ?>);
})(jQuery)
</script>