<?php
/* @var $this Eezy_Note_Block_Article_Grid */ 
?>
<ol class="wrapp_news">
	<?php foreach($this->getCollection() as $article):?>
	<?php /* @var $article Eezy_Note_Model_Article */?>
    <li>
        <div class="user_news_avatar"><img src="<?php echo $article->getImageUrl()?>" width="80" height="80"/></div>
        <div class="wrapp_content_news">
        <a href="<?php echo $article->getUrl()?>" class="title_news"><?php echo $article->getTitle()?></a>
        <span class="meaning_news">Meaning</span><br />
        <span><?php echo $article->getShortDescription()?> <a href="<?php echo $article->getUrl()?>">more.</a></span><br />
        </div>
        <div class="clear"></div>
    </li>
    <?php endforeach;?>
</ol>