<?php
/* @var $this Mage_Core_Block_Template */

/* @var $article Eezy_Note_Model_Article */
$article = $this->getArticle();
?>
<article class="grid_21 float_left">
<div class="wrapp_news detail">
<div class="user_news_avatar">
	<img src="<?php echo $article->getImageUrl()?>" width="100" height="150"/>
	<?php echo $this->getChildHtml('facebook_like');?>
	<?php echo $this->getChildHtml('googleplusone_default');?>
</div>
<div class="wrapp_content_news">
<a href="#" class="title_news"><?php echo $article->getTitle()?></a>
<?php echo $this->getChildHtml('article_tags') ?><br /><br />
<span class="description"><?php echo $article->getDescription()?></span><br />
</div>
<div class="clear"></div>
</div>
<div class="space30"></div>
<div class="content_general">
	<?php echo $article->getContent()?>
    <div>
        <span class="title_news_detail all"><?php echo $this->__('Xem toàn bộ bài viết &gt;&gt;&gt;');?></span>
        <div class="content_news_detail">
        <!-- 
        <div class="content_news_popup">
        <span>People</span><br />
        <span>persons, men, women, children</span><br />
        <div class="link_search"><a href="#">google</a>&nbsp;&nbsp;<a href="#">wiki</a><a class="source" href="#">source:Macmillan</a></div>
        </div>
         -->
        <?php echo $article->getFullEntry()?>
        </div>
    </div>
</div>
<script>
jQuery(function($){
	$(".title_news_detail.all").click(function(e){
		$(".content_news_detail").toggle('slide', {direction: 'up'});
	});
});
</script>
<div class="clear"></div>
</article>