<div id="macmillan" class="content_news_popup" style="display: none;">
    <span class="word"></span><br />
    <span class="mean"></span><br />
    <div class="link_search"><a href="#" class="google" target="_blank" title="This will open new tab">google</a>&nbsp;&nbsp;<a href="#" class="wiki" target="_blank" title="This will open new tab">wiki</a><a class="source" href="#" target="_blank" title="This will open new tab">source:Macmillan</a></div>
</div>