<div id="DivTagCloudFX"></div>
<script type="text/javascript">
	var flashvars = {};
	var params = {};
	params.base = "/media/tag_cloud/";
	params.scale = "noscale";
	params.salign = "tl";
	params.wmode = "transparent";
	params.allowFullScreen = "true";
	params.allowScriptAccess = "always";
	swfobject.embedSWF("/media/tag_cloud/TagCloudFX.swf", "DivTagCloudFX", "300", "200", "9.0.0", false, flashvars, params); 
</script>