<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__($this->getForm()->getTitle())?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Save</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <?php echo $this->getForm()->toHtml()?>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>