<?php /* @var $article Eezy_Note_Model_Article */ ?>
<?php $article = $this->getArticle();?>
<?php if($article):?>
<div class="user_news_avatar">
	<img src="<?php echo $article->getImageUrl()?>" width="100" height="150" />
</div>
<div class="wrapp_content_news">
	<a href="<?php echo $article->getUrl()?>" class="title_news"><?php echo $article->getTitle()?></a>
	<?php
/* @var $this Eezy_Note_Block_Article_View_Tags */

foreach($article->getTagsCollection() as $tag):
/* @var $tag Eezy_Note_Model_Tag */
?>
<a class="tag" href="<?php echo $tag->getUrl() ?>"><span class="meaning_news"><?php echo $tag->getName() ?></span></a>
<?php
endforeach;
?><br /> <span><?php echo $article->getDescription()?> <a
		href="<?php echo $article->getUrl()?>">more.</a></span><br />
</div>
<div class="clear"></div>
<?php endif;?>