<div class="wrapp_posts">
<div class="bar_posts"><h4><?php echo $this->__('Bài viết đáng chú ý')?></h4></div>
<div class="wrapp_content_posts">
<ul class="content_posts">
<?php foreach($this->getHotArticles() as $article):?>
	<li><a href="<?php echo $article->getUrl()?>" title="<?php echo $article->getTitle()?>"><?php echo $article->getTitle()?></a></li>
<?php endforeach;?>
</ul>
</div>
<img style="margin: auto;" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>partners/macmillan/logo2.png">
</div>